import test from 'node:test';
import assert from 'node:assert/strict';
import {buildDailyOwnerText} from '../src/services/dailyReportDelivery.service.js';
const base={instanceId:'fixture',reportDate:'2026-10-06',brand:'Fixture',leads:[],learningNotes:[]};
test('missing metric source cannot become zero or a no-complaints claim',()=>{const text=buildDailyOwnerText({...base,metrics:{}});for(const label of ['Сообщений боту','Передано оператору','Резервных ответов','Ссылок отправлено','Жалобы'])assert.match(text,new RegExp(label+': нет данных'));assert.doesNotMatch(text,/За день жалобы не зарегистрированы/);});
test('explicit measured zero remains a known zero',()=>{const text=buildDailyOwnerText({...base,metrics:{turns:0,escalations:0,fallbacks:0,links_sent:0,complaints:0}});for(const label of ['Сообщений боту','Передано оператору','Резервных ответов','Ссылок отправлено','Жалобы'])assert.match(text,new RegExp(label+': 0'));assert.match(text,/За день жалобы не зарегистрированы/);});
test('null blank and invalid counters remain unavailable',()=>{for(const value of [null,'','   ',NaN,-1]){const text=buildDailyOwnerText({...base,metrics:{complaints:value,turns:value} as any});assert.match(text,/Жалобы: нет данных/);assert.match(text,/Сообщений боту: нет данных/);assert.doesNotMatch(text,/За день жалобы не зарегистрированы/);}});

test('actual Redis reader filters corrupt counter fields before report composition',async(t)=>{const {redisClient}=await import('../src/services/redis.service.js');const {readDailyMetrics}=await import('../src/services/dailyAnalytics.service.js');Object.defineProperty(redisClient,'isReady',{value:true,configurable:true});t.after(()=>{delete (redisClient as any).isReady;});t.mock.method(redisClient,'hGetAll',async()=>({turns:'0',links_sent:'5',complaints:'nonsense',escalations:'',fallbacks:'   ',orders_created:'-1',payments:'Infinity'}));const metrics=await readDailyMetrics('fixture','2026-10-06');assert.deepEqual(metrics,{turns:0,links_sent:5});const text=buildDailyOwnerText({...base,metrics});assert.match(text,/Жалобы: нет данных/);assert.match(text,/Резервных ответов: нет данных/);assert.match(text,/Сообщений боту: 0/);});

test('owner message stays inside gateway limit with maximal complaint detail and explicit omission count',()=>{const cases=Array.from({length:100},()=>({kind:'critical',status:'resolved',createdAt:Date.parse('2026-10-04T20:00:00Z'),updatedAt:Date.parse('2026-10-06T17:00:00Z'),summary:'Длинное неизвестное описание',assignedOperator:'present',resolution:'present'}));const text=buildDailyOwnerText({...base,brand:'Я'.repeat(100),metrics:{turns:1000,complaints:100},caseDetailsAvailable:true,timeZone:'Asia/Almaty',complaintCases:cases});assert.ok(text.length<=4096,'Gateway maximum4096, actual'+text.length);assert.match(text,/Показано \d+ из 100 карточек/);assert.match(text,/Сообщений боту: 1000/);assert.match(text,/Жалобы: 100/);assert.match(text,/Созданных заказов: нет данных/);});
